name: Lobster PyPI Packages

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:

  package:
    name: Build and upload
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel requests twine
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
        run: |
          make upload-main
      - name: Archive wheel files
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: |
            packages/*/dist/*.whl
            packages/*/dist/*.gz
            packages/*/meta_dist/*.whl
            packages/*/meta_dist/*.gz
